# Generated by Django 5.2.10 on 2026-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='url',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
